### ISSUE TITLE
I want to import the library in my project 

### ISSUE THREAD

**Issue by 25Shubham96** [Alikaraki95/Getoffyourphone#1]
please provide me the link through which i can import your library in my project

**Comment by Alikaraki95** [comment]
This isn't a library tho, it's a full project. Just download the .zip and import it via Android Studio.

**Comment by 25Shubham96** [comment]
Hello @Alikaraki95,
Can you help me with how you have imported the @abumoallim "Android-Multi-Select-Dialog" library in your project and changed some of the codes in the library according to your use.

**Comment by Alikaraki95** [comment]
@25Shubham96 that edited library is called "Library" in my project directory, you can grab it by simply importing that folder to your own project. You don't need to add anything just import that Library folder and sync your project. If you need any further assistance reply here :)

**Comment by Alikaraki95** [comment]
@25Shubham96 Did you fix your issue? Shall i close this?

**Comment by 25Shubham96** [comment]
Hello @Alikaraki95 , thanks for your time, I have fixed all my issues a month ago by googling it all, I have done the similar things that you have suggested in the previous comment and modified it according to my need thanks once again, your code helped me a lot. 

Yes, you can close this issue/question.

**Comment by Alikaraki95** [comment]
Thanks & Good Luck.
