### ISSUE TITLE
Sound or Vibrate on open

### ISSUE THREAD

**Issue by iexos** [Alikaraki95/Getoffyourphone#10]
Hi,

I would like to have a stronger backlash when trying to use locked down apps. An option for vibrate and/or sound would be nice. (Personally i would use vibrate only, but sound could be useful as well to leverage social embarressment :))

**Comment by Alikaraki95** [comment]
Actually that's brilliant! I'll add it next update. Thanks!

**Comment by Alikaraki95** [comment]
@iexos I'll be closing this now, feature already added :+1: 

Will be in release 6.0r, thankyou so much for the suggestion.
