### ISSUE TITLE
How to add selected app

### ISSUE THREAD

**Issue by CorentinDy** [Alikaraki95/Getoffyourphone#11]
Hi, 
I'm maybe missing something but I don't find how to add apps to lock..

**Comment by Alikaraki95** [comment]
Hey!

To add apps:

1- Slide left drawer
2- click on Select Apps
3- Pick whatever app you want
4- Profit?

**Comment by CorentinDy** [comment]
Well I feel dumb ! 
I thought the mark was here to show that was the menu corresponding to the current view ..

Thanks 👍
