### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by makmm** [Alikaraki95/Getoffyourphone#12]
Hello! I would like to contribute doing a spanish translation. Is there an easy way to do that? Thanks!

**Comment by Alikaraki95** [comment]
Hey there!

Yes, it's super easy! Fork the project,  grab the strings.xml file and translate it, then put it inside a new folder in res/values-XX , where XX is the language code you're using. 

Here's a [Helpful comment](https://stackoverflow.com/a/23736910) in case you had any trouble.

**Comment by makmm** [comment]
Thanks! Should I translate the huge changelog string and the name of the app? @Alikaraki95
