### ISSUE TITLE
FAQ 

### ISSUE THREAD

**Issue by ewuoso** [Alikaraki95/Getoffyourphone#18]
Had to download your app.  After using it I found it useful.  I lock whatsapp because it distracts me from doing things that need to be done.  I noticed there is no Frequently asked questions section in the app. I am a copywriter, if you don't mind I can draft knew for you

**Comment by Alikaraki95** [comment]
@ewuoso Oh! Okay then feel free to do so, would be much appreciated :grin: !

Thanks for the positive feedback, too.

**Comment by Alikaraki95** [comment]
Abandoned, closing for now.
