### ISSUE TITLE
Blocks forever if end should be after midnight

### ISSUE THREAD

**Issue by iexos** [Alikaraki95/Getoffyourphone#22]
Once it hits midnight, the blocking duration extends by 24h.

**Comment by Alikaraki95** [comment]
Thank you for your feedback! This issue/bug has already been reported, however, i am very busy at the moment (Life, work etc.. ) and I've halted the development of the project, please be patient :)

**Comment by Alikaraki95** [comment]
@iexos 

Hey!

I'll be releasing a test version with the new fix very soon, i hope you can give me some feedback after testing it and see if this issue has been fixed accordingly!

Sorry for the delays.

**Comment by Alikaraki95** [comment]
Closed for the moment as i have released a fix for it. If the issue comes back i'll re-open the ticket. Thanks!

**Comment by iexos** [comment]
Its fixed for me :)

**Comment by Alikaraki95** [comment]
@iexos Awesome! I've got some new goodies  very soon :) PROBABLY this weekend v7 ( or v6.5r ) should be ready :) 

Thanks again ^^ Good day.
