### ISSUE TITLE
Request: Please fix the issues

### ISSUE THREAD

**Issue by Breakfastisready** [Alikaraki95/Getoffyourphone#25]
Dear Developer,

I know this is a duplicate. 

I am a student and my cell-phone addiction is eating away my life. This app is full of bugs but is probably the only one of it's kind out there on Android. Please fix the app and I promise I will donate you in whatever capacity I can!

The major issue is the bug that makes the timer go crazy in the night. This issue has been reported by many other users. Night-time is the period where the app is most useful because turning it on helps me sleep. Please help me.

**Comment by Alikaraki95** [comment]
@Breakfastisready 

Thankyou for your sincere suggestion. I'm still working on other things in life and can't find proper time for the project, however - i will start back at again in the following weeks. I will be working on the Night-Time bug first as it's the most important bug for now!

Please be patient & Happy Holidays!

**Comment by Alikaraki95** [comment]
@Breakfastisready 

Hey!

I'll be releasing a test version with the new fix very soon, i hope you can give me some feedback after testing it and see if this issue has been fixed accordingly!

Sorry for the delays.

**Comment by Alikaraki95** [comment]
Closed for the moment as i have released a fix for it. If the issue comes back i'll re-open the ticket. Thanks!

**Comment by Breakfastisready** [comment]
Did you roll out the update on F-Droid?

**Comment by Alikaraki95** [comment]
@Breakfastisready 

Yes. Takes about 5 days fir F-droid to pick it up, maybe less :smile:

**Comment by Alikaraki95** [comment]
@Breakfastisready 

You can download the update from here btw. F-droid merges all changes from Github, so te release i uploaded here is the same one used in F-droid - except the signature. Just thought I'd mention that :) 

Please tell me if the issue is fixed once you test it? I tested it on my devices and it worked just fine.
