### ISSUE TITLE
Complains that timer is already running when it isnt

### ISSUE THREAD

**Issue by iexos** [Alikaraki95/Getoffyourphone#27]
I cant give you many more details, the title says it all. I suspect that the service is stopping in a way that is not expected.

**Comment by iexos** [comment]
Easy way to reproduce: start the service, go to App Info and "Force Stop". Best practice is to check if the service is actually alive.

**Comment by Alikaraki95** [comment]
@iexos 

It indeed happens when the service stops unexpectedly. This happens when either: System force stops the app by itslef - User force stops the app - phone restart. 

Can you tell me:

- Your phone, your OS version
- If you restarted the phone by any chance?

**Comment by Alikaraki95** [comment]
@iexos Yep, that explains it! I will make a OnReboot detection that resets the service if the phone battery dies/reboot happens. 

Thanks a lot :)

**Comment by iexos** [comment]
I would be in favor of detecting the force stop as well. For example i already had this situation: i block my email app so i dont check constantly, but then i know an important email arrives that i have to check. I force stop the app to access my email, but then i have to reinstall your app again as its useless otherwise.

I can see the other argument though, that you might want to force the user to reinstall and have to set all the settings again to male circumventing this app more of a hassle.

**Comment by Alikaraki95** [comment]
@iexos 

I see your point. 

When this happens, you don't need to reinstall the app, you can just clear app data and it works just fine ( you have to select apps again, tho. )

Detecting a phone reboot is easy, but it's almost impossible to detect a force stop ( that's the whole idea of a force stop. But I'll implement something very smart and silly :p )

I'll make a button that says : Fix Timer Already running, which resests the service only so anyone who gets stuck, can simply click the button - sounds good?

**Comment by iexos** [comment]
(Maybe you didnt see my edit ;) )

Wouldnt that button would be functionally "stop blocking apps"? If not, its fine for me as a workaround

**Comment by Alikaraki95** [comment]
@iexos 

Oh my bad, well, i can make a few workarounds and test all scenarios first! If i find a working one I'll give it a shot :) 

And yes settings are lost, i believe i made it that way for a while to avoid a database crash. I'll fix it later :)

**Comment by Alikaraki95** [comment]
@iexos 

- Feature has been implemented (Phone Reboot detection )

I can't detect a user force stop,  so, i'll leave it as a hassle and punishment for users who force stop the app, so they'll have to: Clear app data > Edit the settings again > Select apps again, which, eventually, might encourage them not to force stop :) 

Patch is in the upcoming v6.2r. Issue closed for now!

Thanks.
