### ISSUE TITLE
How to donate?

### ISSUE THREAD

**Issue by Breakfastisready** [Alikaraki95/Getoffyourphone#28]
I see that there is a Donation App on the Google Play store to raise funds. Is there any other way to donate if someone doesn't want to contribute money to Google, like PayPal for example?

**Comment by Alikaraki95** [comment]
Sorry i couldn't reply to you about this earlier. I've added a new donate button in Readme. Donations are very much appreciated, but not needed. 

Thanks for showing positive feedback, means a lot!
