### ISSUE TITLE
Is there any way to stop these apps from sending notifications? 

### ISSUE THREAD

**Issue by moshpirit** [Alikaraki95/Getoffyourphone#29]
Is like not to be distracted by these apps and I think a wonderful way to do it would be forcing these apps not to show me anything at all.

**Comment by moshpirit** [comment]
I would include a button, though. I like to always have the option to choose what do I want, but thank you so much!!

**Comment by Alikaraki95** [comment]
@moshpirit alright no worries, gotcha :smile:

**Comment by Alikaraki95** [comment]
@moshpirit 
Feature Completed (M+ Only) - Will be added in v6.2r

Thanks!

**Comment by moshpirit** [comment]
Hi again! I saw the last version and it's great but I meant to just hide the notifications of the selected apps, not all notifications 😅

**Comment by Alikaraki95** [comment]
@moshpirit 

Hey! I know that was what you asked for, but i'm still hesitant whether i implement that or not. Reason?

Letting the app block specific notifications means my app will have access to all your notifications, with a NotificationListener , and this isn't really likable even from my side. I don't know if you get my point, but this basically means the app will have access even to your actually content inside the notifications - and that might repel some users and think the app might be storing these somewhere. For the meantime, it will be a DND kind of blockage. I'll update you later on :) I want to change the whole concept of choosing apps and the screen where you select apps, so maybe i'll add the feature when everything is changed!

Good day.

**Comment by moshpirit** [comment]
OK thanks! Seems like a black o white decision, so I think you chose well. What a pity there's no middle ground. I'll research on the Internet when I finish my exams. Maybe there's a solution for this :)

Disclaimer: people don't trusting the app seems kind of dumb since the app is free software but I understand the point though. Thanks a lot for explaining it to me!
Have a nice day!
