### ISSUE TITLE
Countdown of timer stops when phone goes to sleep

### ISSUE THREAD

**Issue by japhir** [Alikaraki95/Getoffyourphone#3]
I started a 30 min test yesterday evening to see how the app worked and to stop me from browsing Reddit before bed 😉. However, when I woke up it still had 17 minutes to go. After playing around for a bit, it appears that the timer doesn't continue once the screen goes idle. I have turned off battery optimisation for the app. Cheers! 

EDIT: I'm on Android 8.1.0 on a Nexus 5x (hammerhead)

**Comment by japhir** [comment]
Ahh that could be it, just ran it for 30 minutes and it went fine in idle mode. Cheers

**Comment by japhir** [comment]
I reproduced it by:
- Turn on the 30 minute blocker at a quarter to twelve
- turn on airplane mode (went to bed) and sleep tracking
- wake up to find the timer still running
- turn off airplane mode
- timer doesn't run in the background, only when the app is open? Not sure.

**Comment by japhir** [comment]
Also, the time display is weird sometimes, it displayed, for example: 15:2:03 (in stead of 15:02:03).

**Comment by Alikaraki95** [comment]
@japhir Hey

The timer should work perfectly fine even if the app is closed/in background.

I'll be testing it regarding airplane mode or so, given that the app has nothing to do with wireless / data connectivity. Thanks for the feedback, i'll work on it when i'm available!

And the time display, that is intended. I can make a setting to show both ways, if you want :)

**Comment by Alikaraki95** [comment]
@japhir Are you still experiencing the issue?

**Comment by japhir** [comment]
I think the issue is the same as the other one, it flips out a little if you set the timer before 00:00. So if there's an issue for that, this can be closed.

Haven't used the app much because I decided to just remove the addictive apps from my phone 😉

**Comment by Alikaraki95** [comment]
@japhir Okay, thanks! I found the source of this bug, however, i'm unable to fix it fast. I'll be looking into it more. I will release a version soon without this fix so i can work on it :)

**Comment by Alikaraki95** [comment]
Closed for the moment as i have released a fix for it. If the issue comes back i'll re-open the ticket. Thanks!
