### ISSUE TITLE
No app shown despite permissions 
(mistake were made) 

### ISSUE THREAD

**Issue by traceur920** [Alikaraki95/Getoffyourphone#33]
My bad, I was blind. Didn't see the left menu.
Marking as closed.

**Comment by Alikaraki95** [comment]
@traceur920 

Actually, this is my bad! I'll have to add an action bar and show the users that there's something on the left side! My bad.

Thanks for the report.

**Comment by traceur920** [comment]
That's actually a good idea.

Anyway I've now what I think is a real issue with the app.
On Oneplus 3T (OxygenOS) I've run the timer a couple of times and, after the set amount of time had passed, I've seen my wifi toggle reverting to "on" status but as soon as I've tried to open a locked app, the "locked" screen popped up with no timer at all and simply won't leave until I would force kill the GetOffYourPhone process or open again the GetOffYourPhone app a couple of time.

Here is a short video:
https://streamable.com/6tsa4

I can't see in the Readme if this is a desired behavior. If that's not the case do you prefer I open a new issue for this?

**Comment by Alikaraki95** [comment]
@traceur920

Hmm. That's indeed weird! Never seen it before. Did you try opening GOYP itself? What do you see inside it when that happens? That usually means the timer service didn't stop properly. 

Next time this happens can you please tell me what do you see when you open it? Thanks for the report!

**Comment by traceur920** [comment]
If I do not open the app, the behavior is what already shown, and seems to go on indefinitely. 

If instead (at some time after the timer runs out) I try to open GOYP, it simply acts like normal, saying that no timer Is running and ready to go for another one, and the activity "locked" stops from showing up on previously locked apps.
Will report if something different occurs!

**Comment by Alikaraki95** [comment]
So everything works fine if you open the app before you try to open a previously locked app.. okay. Please tell me if this occurres again :) I think i know why this is happening.

**Comment by traceur920** [comment]
As a side note, I understand your decision to not change the "timer is already running" as a punishment when someone kills the app, but this is the third time that I have to go through the hassle of choosing which app to lock because I've inadvertently closed all the recent apps from my phone (and so I've killed the GOYP itself) and I'm starting to think that a "fix/reset timer" button should be present.
(128 GB phone, a _lot_ of apps to lock... Maybe I need to do some cleaning) 

(Also take in mind that the error "timer is already running" seems to appear even after the amount of time has passed and the apps have been unlocked. 

And I'll say quite a bit after as I'm writing this now as I closed the apps and opened GOYP, while the timer was set for an hour about 2 hours ago. 

I'm sorry I have no time to try to reproduce these errors systematically, so take them as a mere hint)

**Comment by Alikaraki95** [comment]
@traceur920 

I understand your point very clearly.

But you need to understand that such a button can and be also used to just get out of lockdown.. I'll actually test it out :) if it works and users use it only to FIX such an issue instead of just canceling the lockdown , I'll leave it.

Sorry if you're encountering these annoying bugs, I'll try and tackle things down. 

Thankyou for reporting and suggesting ideas!
