### ISSUE TITLE
New logo for your project

### ISSUE THREAD

**Issue by twingenious** [Alikaraki95/Getoffyourphone#7]
Hello! 😃 I'm a designer, happy to contribute to open source projects and I think that a new logo for your project would be awesome 

So, if you agree with this you can tell me what ideas you have for this or what are your expectations for a logo that could be fitted with the project.

I want to remember that this is totally free and this has not any compromise or something, so you can say no or stop this anytime you want.

**Comment by Alikaraki95** [comment]
@twingenious Hey!

That's absolutely wonderful & kind if you! Yes of course I'd like a new logo! Do you have any thoughts in mind? 

How did you find my project? Man you made my day :grin: !

My old logo was a bit small and a low resolution, it was a clock on fire ( burning ) that i found online as a template, and then changed it to the current one. Btw my app got removed off app store (temporarily) duo to the new Google play store Privacy policy wave ( tons of apps got removed )

It'll need a bit of time, maybe a couple of hours for it to get back. Thought I'd tell ya!

**Comment by twingenious** [comment]
Perfect! 😉 let's start. 
well, I found your project looking for new repositories of apps that have a cool idea but need a bit of help with the design part💪.

the idea is that the logo looks minimalist but at the same time original. 

I think that the padlock and the clock are minimalist, but they look generic, so can have a confusion with a google icon.

**Comment by Alikaraki95** [comment]
The Hero we need :stuck_out_tongue_closed_eyes:

I'm open to any design you offer! You can draw a template or something so you won't work hard on it before we agree :) sounds good? I mean, whatever you're comfortable with :blush:

**Comment by twingenious** [comment]
![firstidea](https://user-images.githubusercontent.com/43223329/45722611-2b804c00-bb7b-11e8-83e3-7453d07d9da9.png)

what do you think about this idea?☝️
this is a concept that I have imagined,  and I think that this fits without overload the icon or to be hard to see.

the four squares represent the applications of your mobile and in the center like a padlock but in a different way, that wraps up all applications.

if you agree with this idea, then I put all the shadow, reflections, and extra elements.for make it looks great and presentable.😃

**Comment by Alikaraki95** [comment]
That looks smart. I like it. However, will the boxes stay colored or are you going to replace them with sample apps ?

I love the chains too! ( If the can be properly visible )

**Comment by twingenious** [comment]
> That looks smart. I like it. However, will the boxes stay colored or are you going to replace them with sample apps ?
> 
> I love the chains too! ( If the can be properly visible )

The boxes will have a simple icon of most relevant applications that a mobile has, such as the settings, music, calls, etc.

but without copying from other icons, just like representative shapes of their meaning.

**Comment by Alikaraki95** [comment]
Love the concept then! @twingenious

**Comment by twingenious** [comment]
![getoffyourphone](https://user-images.githubusercontent.com/43223329/45788707-21794e80-bc4a-11e8-9721-3df8a3209359.png)

what do you think? do you like the colors?

**Comment by Alikaraki95** [comment]
@twingenious it looks great. Just the lower left green is too bright! Maybe try to tone it down or try to make the colors match my app theme? It's a blackout, with only blue, and the icon is shown inside the app as well.

**Comment by twingenious** [comment]
Sure, you are right, what you say if we try with a blue scale? , I mean , that the colors of the boxes with a blue scale, I thought about a grey or black scale but as you say , the logo is showed within the app in which is already dark

**Comment by twingenious** [comment]
Can you tell me the hexadecimal color of the blue that you use or you want to use? 
Or any other color that you want to use

**Comment by Alikaraki95** [comment]
Sure. I'm not home right now, but from my colors.xml, this is the hex i'm using #1E88E5 , it doesn't have to be black or white, but just a bit blue to go along with the theme :) i hope this isn't too much for you :smile:

**Comment by twingenious** [comment]
@Alikaraki95 the opposite sir, because there isn't grace in a logo that you don't want to use. the idea is that you think that the logo fits totally with your project.

**Comment by twingenious** [comment]
![sizes](https://user-images.githubusercontent.com/43223329/45853792-3c64c500-bd15-11e8-85a6-4dce701b47b2.png)

**Comment by Alikaraki95** [comment]
@twingenious i love it :) Looks perfect now! Do you like it?

**Comment by twingenious** [comment]
I like a lot and I'm glad that you love it too😜.
I will make the pull request with the images in their respective resolutions for merge it with your project😎

**Comment by Alikaraki95** [comment]
@twingenious Awesome. Before you pr, i wanna ask if the yellow fade is intended ?

**Comment by twingenious** [comment]
no bro just was a mistake adding the colors, one of the channels of the RGB had a wrong value, but it is already fixed.😆

**Comment by twingenious** [comment]
![sizes](https://user-images.githubusercontent.com/43223329/45887571-0877b700-bd8a-11e8-9fad-ba3a6cfbb09c.png)

Check bro

**Comment by Alikaraki95** [comment]
@twingenious This looks fantastic!

**Comment by Alikaraki95** [comment]
[Merged](https://github.com/Alikaraki95/Getoffyourphone/commit/b10b15534fc3088def2ddf9a9f2ed1ed3b26a786)

Thank you so much! I'll release the next version soon, but it'll take a lot of time. I will also change the banner and screenshots in PS. Next update's gonna take some time, lots of changes ( if i manage to succeed with implementations ).

Again, thank you so much mate! :smile: @twingenious

**Comment by twingenious** [comment]
Thanks to you, I appreciate it
