### ISSUE TITLE
Rename "desired counter"

### ISSUE THREAD

**Issue by neomodern** [Alikaraki95/Getoffyourphone#9]
It's not that clear that this is just the number of times until the motivation image is shown. 

Maybe something like "No. of attempts until image".

**Comment by Alikaraki95** [comment]
You're right. I've been meaning to change this for a long time, thanks for the reminder! 

Idea: do you think Totally removing this will affect anyone? I might remove this feature once and for all.

**Comment by neomodern** [comment]
I like the idea just not how it's implemented. It might be best to instead have it as a setting on another screen e.g. "show motivational image after x locked app open attempts"

**Comment by Alikaraki95** [comment]
I'll close this issue now, as this has been removed in the upcoming release (6.0r)!

Thankyou so much for the suggestion, it made me make a whole new feature because of it. :+1:
